package com.example.ants.db.mapper.base;

import com.example.ants.db.entity.TaskStatus;
import com.example.ants.db.entity.TaskStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TaskStatusBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_status
     *
     * @mbg.generated
     */
    long countByExample(TaskStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_status
     *
     * @mbg.generated
     */
    int deleteByExample(TaskStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_status
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_status
     *
     * @mbg.generated
     */
    int insert(TaskStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_status
     *
     * @mbg.generated
     */
    int insertSelective(TaskStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_status
     *
     * @mbg.generated
     */
    List<TaskStatus> selectByExampleWithRowbounds(TaskStatusExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_status
     *
     * @mbg.generated
     */
    List<TaskStatus> selectByExample(TaskStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_status
     *
     * @mbg.generated
     */
    TaskStatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_status
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TaskStatus record, @Param("example") TaskStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_status
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TaskStatus record, @Param("example") TaskStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_status
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TaskStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_status
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TaskStatus record);
}