package com.example.ants.db.mapper.base;

import com.example.ants.db.entity.UserDetails;
import com.example.ants.db.entity.UserDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserDetailsBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbg.generated
     */
    long countByExample(UserDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbg.generated
     */
    int deleteByExample(UserDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbg.generated
     */
    int insert(UserDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbg.generated
     */
    int insertSelective(UserDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbg.generated
     */
    List<UserDetails> selectByExampleWithRowbounds(UserDetailsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbg.generated
     */
    List<UserDetails> selectByExample(UserDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbg.generated
     */
    UserDetails selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserDetails record, @Param("example") UserDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserDetails record, @Param("example") UserDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserDetails record);
}