/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';


/**
 * SampleControllerApi - axios parameter creator
 * @export
 */
export const SampleControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary index
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        indexUsingGET: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/sample`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SampleControllerApi - functional programming interface
 * @export
 */
export const SampleControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SampleControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary index
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async indexUsingGET(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.indexUsingGET(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SampleControllerApi - factory interface
 * @export
 */
export const SampleControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SampleControllerApiFp(configuration)
    return {
        /**
         * 
         * @summary index
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        indexUsingGET(options?: any): AxiosPromise<string> {
            return localVarFp.indexUsingGET(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SampleControllerApi - object-oriented interface
 * @export
 * @class SampleControllerApi
 * @extends {BaseAPI}
 */
export class SampleControllerApi extends BaseAPI {
    /**
     * 
     * @summary index
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SampleControllerApi
     */
    public indexUsingGET(options?: AxiosRequestConfig) {
        return SampleControllerApiFp(this.configuration).indexUsingGET(options).then((request) => request(this.axios, this.basePath));
    }
}


