---

spring:
  datasource:
    username: sample
    password: sample
    thymeleaf:
      prefix: file:src/main/resources/templates/

ants:
  datasource:
    host: 127.0.0.1
    port: 3306
  security:
    csrf: false
