package com.example.ants.db.entity;

public class TaskStatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_status.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_status.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_status
     *
     * @mbg.generated
     */
    public TaskStatus(Integer id, String status) {
        this.id = id;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_status
     *
     * @mbg.generated
     */
    public TaskStatus() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_status.id
     *
     * @return the value of task_status.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_status.id
     *
     * @param id the value for task_status.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_status.status
     *
     * @return the value of task_status.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_status.status
     *
     * @param status the value for task_status.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }
}