package com.example.ants.db.entity;

public class UserDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_details.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_details.mail
     *
     * @mbg.generated
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_details.github_name
     *
     * @mbg.generated
     */
    private String githubName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_details.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbg.generated
     */
    public UserDetails(Integer userId, String mail, String githubName, String country) {
        this.userId = userId;
        this.mail = mail;
        this.githubName = githubName;
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_details
     *
     * @mbg.generated
     */
    public UserDetails() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_details.user_id
     *
     * @return the value of user_details.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_details.user_id
     *
     * @param userId the value for user_details.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_details.mail
     *
     * @return the value of user_details.mail
     *
     * @mbg.generated
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_details.mail
     *
     * @param mail the value for user_details.mail
     *
     * @mbg.generated
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_details.github_name
     *
     * @return the value of user_details.github_name
     *
     * @mbg.generated
     */
    public String getGithubName() {
        return githubName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_details.github_name
     *
     * @param githubName the value for user_details.github_name
     *
     * @mbg.generated
     */
    public void setGithubName(String githubName) {
        this.githubName = githubName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_details.country
     *
     * @return the value of user_details.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_details.country
     *
     * @param country the value for user_details.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country;
    }
}